### ISSUE TITLE
loading-json-in-kha.html

### ISSUE THREAD

**Issue by sh-dave** [ashes999/learnhaxe#2]
hi, not sure if it's a good place to post this, but you don't need to keep filenames distinct. you can use:

```
/assets
   /folder1
      map.txt
   /folder2
      map.txt
```

in your ```khafile.js``` add the assets like this
```js
project.addAssets('assets/**', {
    nameBaseDir: 'assets',
    destination: '{dir}/{name}',
    name: '{dir}/{name}'
});
```

and then you can access them with
```haxe
kha.Assets.blobs.folder1_map_txt
kha.Assets.blobs.folder2_map_txt
```

this works for all asset types (images, sounds, ...) not just blobs.

**Comment by sh-dave** [comment]
Also just updated the asset section in Kha's wiki (https://github.com/Kode/Kha/wiki/khafile.js#adding-assets)

**Comment by ashes999** [comment]
Thanks! I guess you didn't see the comments section because it loads insecurely (Chrome asks you to run it manually). I rolled your changes into the post, including a link to your updates on the Kha wiki.

Sorry, I don't have a lot of experience with Kha. I didn't test this before blogging about it. (Bad move, in hindsight.)

**Comment by sh-dave** [comment]
Oh, yeah, if i load the site via http i actually see the comments section after unblocking and whatnot.
And no worries, a lot of stuff is kinda hidden in Kha and would benefit from more proper documentation.
